apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.projectName }}
  labels:
    mrn: {{ .Values.projectName }}
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: web-ingress
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
spec:
  rules:
  - host: local.skilld.cloud
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ .Values.projectName }}
            port:
              number: 80
  tls:
  - hosts:
    - local.skilld.cloud
    secretName: {{ .Values.projectName }}-tls
