apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.projectName }}
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
  - name: mailhog
    port: 8025
    protocol: TCP
  selector:
    mrn: {{ .Values.projectName }}