version: "2"

services:

# Override base service.
  php:
    volumes:
      - ./configs/90-mail.ini:/usr/local/etc/php/conf.d/90-mail.ini:z
      - ./configs/ssmtp.conf:/etc/ssmtp/ssmtp.conf:z
# Uncomment next line if you need PHP XDebug.
#    command: php-fpm -F -d zend_extension=xdebug.so
# By default for AKIWCARL01 host used IP of dev WS.
    extra_hosts:
      - "AKIWCARL01:163.172.103.109"

#  adminer:
#    image: dockette/adminer:mysql-php7
#    container_name: "${COMPOSE_PROJECT_NAME}_adminer"
#    links:
#      - mysql:mysql
#    depends_on:
#      - mysql
#    networks:
#      - front

  mailhog:
    image: skilldlabs/mailhog
    container_name: "${COMPOSE_PROJECT_NAME}_mail"
    restart: always
    networks:
      - front

# Mount local folder with ssl keys.
#  nginx:
#    volumes:
#     - /home/waspper/SKILLD/akiem/ssl:/etc/nginx/ssl:Z
